### ISSUE TITLE
Throws exception with every dependency installed properly

### ISSUE THREAD

**Issue by shardator** [coldfix/git-filter-tree#10]
Hi, Could you please tell me why do I get this output? I've installed everything (`pygit2`, `setuptools`, ran `setup.py`, though I had to manually add read_file function to it, etc.)

```
$ ~/git-filter-tree/git-dir2mod $(pwd)/gitlab-src-nomaps mvp/launchers/maps out-gitlab-src-nomaps out-gitlab-maps
Cloning into bare repository 'out-gitlab-maps'...
done.
Cloning into bare repository '/tmp/gitlab-src-nomaps-submodule'...
done.


/tmp/gitlab-src-nomaps-submodule: Extracting folder 'mvp/launchers/maps'
========================================================================
Rewrite 8e61b79f7778c23dd35cc5315be6bce17ad5a48d (36/36) (0 seconds passed, remaining 0 predicted)    
Ref 'refs/heads/gitlab' was rewritten
Ref 'refs/tags/final-without-mapseg' was rewritten
Ref 'refs/tags/old-hg-ver' was rewritten
Ref 'refs/tags/release-0.0.0' was rewritten
Ref 'refs/tags/release-0.0.1' was rewritten
Ref 'refs/tags/release-0.0.12' was rewritten
Ref 'refs/tags/release-0.0.2' was rewritten
Ref 'refs/tags/test-0.0.1' was rewritten
Ref 'refs/tags/test-1.2.3' was rewritten


/tmp/gitlab-src-nomaps-submodule: Deleting disconnected branches
================================================================


/tmp/gitlab-src-nomaps-submodule: Creating index: TREE -> COMMIT
================================================================
= STARTING =
Traceback (most recent call last):
  File "/home/gnagy/git-filter-tree/git_filter_tree/__main__.py", line 16, in main
    mod = import_module("git_filter_tree."+args[0], "git_filter_tree")
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/git_filter_tree-2.1.0-py3.5.egg/git_filter_tree/dir2mod.py", line 20, in <module>
    from .tree_filter import TreeFilter, cached
  File "/usr/local/lib/python3.5/dist-packages/git_filter_tree-2.1.0-py3.5.egg/git_filter_tree/tree_filter.py", line 18, in <module>
    import pygit2
  File "/home/gnagy/.local/lib/python2.7/site-packages/pygit2/__init__.py", line 32, in <module>
    from _pygit2 import *
ImportError: /home/gnagy/.local/lib/python2.7/site-packages/_pygit2.so: undefined symbol: _Py_ZeroStruct

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gnagy/git-filter-tree/git_filter_tree/__main__.py", line 23, in <module>
    sys.exit(main())
  File "/home/gnagy/git-filter-tree/git_filter_tree/__main__.py", line 18, in main
    mod = import_module(args[0], "git_filter_tree")
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/gnagy/git-filter-tree/git_filter_tree/dir2mod.py", line 20, in <module>
    from .tree_filter import TreeFilter, cached
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by coldfix** [comment]
Hi,

your trace-back shows that while you're running python 3.5, somehow the pygit extension for python 2.7 is loaded -> which is obviously binary incompatible and errors due to missing symbols.

I've never seen this problem and I'm not sure how this would emerge. Maybe, do you have any PYTHONPATH settings or similar?

**Comment by coldfix** [comment]
Could also be due to PATH or possibly LD_LIBRARY_PATH settings. I recommend you open a new terminal, make sure to deactivate any previous virtual environment (if you activate anything in your bashrc/zshrc), make sure there is nothing significant in `env | grep python`, then recreate py3 environment and try again to reinstall.

>>> , though I had to manually add read_file function to it, etc.)

I must have somehow removed that and didn't even notice :/, Thanks for the info!

**Comment by coldfix** [comment]
Anyway, I don't believe this issue is related to this package specifically.
