### ISSUE TITLE
tag has no tree_id

### ISSUE THREAD

**Issue by msillence** [coldfix/git-filter-tree#9]
Running the shell script to unpack my repo I get the following error:

  File "/mnt/git-filter-tree/git_filter_tree/tree_filter.py", line 215, in rewrite_root_commit
    ids = [commit.tree_id] + commit.parent_ids
AttributeError: '_pygit2.Tag' object has no attribute 'tree_id'

looks like we're not expecting a tag at this point

full stack trace is:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/git-filter-tree/git_filter_tree/__main__.py", line 23, in <module>
    sys.exit(main())
  File "/mnt/git-filter-tree/git_filter_tree/__main__.py", line 19, in main
    return mod.main(args[1:])
  File "/mnt/git-filter-tree/git_filter_tree/tree_filter.py", line 289, in main
    loop.run_until_complete(future)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/mnt/git-filter-tree/git_filter_tree/tree_filter.py", line 301, in filter
    await self.filter_branch(refs))
  File "/mnt/git-filter-tree/git_filter_tree/tree_filter.py", line 327, in filter_branch
    new = await self.rewrite_root(old.hex)
  File "/mnt/git-filter-tree/git_filter_tree/tree_filter.py", line 215, in rewrite_root_commit
    ids = [commit.tree_id] + commit.parent_ids
AttributeError: '_pygit2.Tag' object has no attribute 'tree_id'

**Comment by msillence** [comment]
Ooops I'm using pygit 0.27.... will try again with 0.26

**Comment by coldfix** [comment]
Hey, thanks for reporting. I didn't look in detail, but it looks like the error is due to passing a tag where the module currently expects a commit. What is your command line? Can you try passing the commit referred to by the tag instead of the tag itself?
